%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/m/work/slam/data/tum/fr1_xyz
#dataset_dir: /home/m/work/slam/data/tum/rgbd_dataset_freiburg3_long_office_household

# camera intrinsics
# 
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

camera.depth_scale: 5000

# VO paras
number_of_features: 500
scale_factor: 1.2
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1
